
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AlumMati
 */
public class App_Hamburgueseria extends javax.swing.JFrame {
    
    //ArrayList para armanezar los pedido y valores
    ArrayList<String>pedido = new ArrayList<>();
    ArrayList<Double>valores = new ArrayList<>();
    
    public App_Hamburgueseria() {
        
        //TITULO PANTALLA CENTRALIZACIÓN DE LA PANTALLA
        setTitle("TPV - Hamburguesería Los Santos");
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * Creates new form App_Hamburgueseria
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonDobleHamb = new javax.swing.ButtonGroup();
        butonExtraQueso = new javax.swing.ButtonGroup();
        butonExtraPatatas = new javax.swing.ButtonGroup();
        butonReparto = new javax.swing.ButtonGroup();
        butonTipoHamburguesa = new javax.swing.ButtonGroup();
        butonTipoPan = new javax.swing.ButtonGroup();
        butonTipoBebida = new javax.swing.ButtonGroup();
        butonTipoPatatas = new javax.swing.ButtonGroup();
        butonTipoSalsa = new javax.swing.ButtonGroup();
        panelGeneral = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        tituloHamburgueseria = new javax.swing.JLabel();
        pantallaMostrarArea = new javax.swing.JScrollPane();
        pantallaMostrar = new javax.swing.JTextArea();
        doubleHambur = new javax.swing.JLabel();
        extraQueso = new javax.swing.JLabel();
        extraPatatas = new javax.swing.JLabel();
        butonSiHambur = new javax.swing.JRadioButton();
        butonNoHambur = new javax.swing.JRadioButton();
        butonSiQueso = new javax.swing.JRadioButton();
        butonNoQueso = new javax.swing.JRadioButton();
        butonSiPatatas = new javax.swing.JRadioButton();
        butonNoPatatas = new javax.swing.JRadioButton();
        descuentoCliente = new javax.swing.JButton();
        butonIVA = new javax.swing.JButton();
        cerrarPedido = new javax.swing.JButton();
        repartoDomic = new javax.swing.JLabel();
        butonSiReparto = new javax.swing.JRadioButton();
        butonNoReparto = new javax.swing.JRadioButton();
        tituloMostrarResultado = new javax.swing.JLabel();
        hamburguesaPollo = new javax.swing.JRadioButton();
        hamburguesaCerdo = new javax.swing.JRadioButton();
        hamburguesaTernera = new javax.swing.JRadioButton();
        hamburguesaVegana = new javax.swing.JRadioButton();
        panNormal = new javax.swing.JRadioButton();
        panIntegral = new javax.swing.JRadioButton();
        panCentano = new javax.swing.JRadioButton();
        bebidaCocaCola = new javax.swing.JRadioButton();
        bebidaLimon = new javax.swing.JRadioButton();
        bebidaNaranja = new javax.swing.JRadioButton();
        bebidaAgua = new javax.swing.JRadioButton();
        bebidaCerveza = new javax.swing.JRadioButton();
        bebidaVino = new javax.swing.JRadioButton();
        patatasFritas = new javax.swing.JRadioButton();
        patatasGajo = new javax.swing.JRadioButton();
        calcularPedido = new javax.swing.JButton();
        novoPedido = new javax.swing.JButton();
        panelElegirHamburguesa = new javax.swing.JPanel();
        tituloHamburgueseria1 = new javax.swing.JLabel();
        panelElegirPan = new javax.swing.JPanel();
        tituloHamburgueseria2 = new javax.swing.JLabel();
        panelElegirBebida = new javax.swing.JPanel();
        tituloHamburgueseria3 = new javax.swing.JLabel();
        panelElegirPatatas = new javax.swing.JPanel();
        tituloHamburgueseria4 = new javax.swing.JLabel();
        panelExtrasAdicionales = new javax.swing.JPanel();
        tituloHamburgueseria5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarTotal = new javax.swing.JTextArea();
        panelElegirSalsas = new javax.swing.JPanel();
        tituloSalsas = new javax.swing.JLabel();
        elegirSalsaKetchup = new javax.swing.JCheckBox();
        elegirSalsaBarbacoa = new javax.swing.JCheckBox();
        elegirSalsaMostaza = new javax.swing.JCheckBox();
        elegirSalsaNo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGeneral.setBackground(new java.awt.Color(0, 51, 51));
        panelGeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        panelGeneral.setForeground(new java.awt.Color(176, 241, 241));
        panelGeneral.setToolTipText("");
        panelGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelTitulo.setBackground(new java.awt.Color(0, 153, 102));

        tituloHamburgueseria.setBackground(new java.awt.Color(0, 102, 0));
        tituloHamburgueseria.setFont(new java.awt.Font("Calibri", 3, 30)); // NOI18N
        tituloHamburgueseria.setForeground(new java.awt.Color(255, 255, 255));
        tituloHamburgueseria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloHamburgueseria.setText("Hamburguesería Los Santos");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addComponent(tituloHamburgueseria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamburgueseria)
        );

        pantallaMostrar.setColumns(20);
        pantallaMostrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pantallaMostrar.setRows(5);
        pantallaMostrarArea.setViewportView(pantallaMostrar);

        doubleHambur.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        doubleHambur.setForeground(new java.awt.Color(255, 255, 255));
        doubleHambur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doubleHambur.setText("Hambur. Doble(+2€)");

        extraQueso.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        extraQueso.setForeground(new java.awt.Color(255, 255, 255));
        extraQueso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extraQueso.setText("Extra de Queso(+0,50€)");

        extraPatatas.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        extraPatatas.setForeground(new java.awt.Color(255, 255, 255));
        extraPatatas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extraPatatas.setText("Extra de Patatas(+1€)");

        butonDobleHamb.add(butonSiHambur);
        butonSiHambur.setForeground(new java.awt.Color(255, 255, 255));
        butonSiHambur.setText("Si");
        butonSiHambur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonSiHamburActionPerformed(evt);
            }
        });

        butonDobleHamb.add(butonNoHambur);
        butonNoHambur.setForeground(new java.awt.Color(255, 255, 255));
        butonNoHambur.setText("No");
        butonNoHambur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonNoHamburActionPerformed(evt);
            }
        });

        butonExtraQueso.add(butonSiQueso);
        butonSiQueso.setForeground(new java.awt.Color(255, 255, 255));
        butonSiQueso.setText("Si");
        butonSiQueso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonSiQuesoActionPerformed(evt);
            }
        });

        butonExtraQueso.add(butonNoQueso);
        butonNoQueso.setForeground(new java.awt.Color(255, 255, 255));
        butonNoQueso.setText("No");
        butonNoQueso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonNoQuesoActionPerformed(evt);
            }
        });

        butonExtraPatatas.add(butonSiPatatas);
        butonSiPatatas.setForeground(new java.awt.Color(255, 255, 255));
        butonSiPatatas.setText("Si");
        butonSiPatatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonSiPatatasActionPerformed(evt);
            }
        });

        butonExtraPatatas.add(butonNoPatatas);
        butonNoPatatas.setForeground(new java.awt.Color(255, 255, 255));
        butonNoPatatas.setText("No");
        butonNoPatatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonNoPatatasActionPerformed(evt);
            }
        });

        descuentoCliente.setBackground(new java.awt.Color(255, 106, 0));
        descuentoCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        descuentoCliente.setText("Desc. 20%");
        descuentoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descuentoClienteActionPerformed(evt);
            }
        });

        butonIVA.setBackground(new java.awt.Color(255, 106, 0));
        butonIVA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butonIVA.setText("IVA 21%");
        butonIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonIVAActionPerformed(evt);
            }
        });

        cerrarPedido.setBackground(new java.awt.Color(204, 0, 0));
        cerrarPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cerrarPedido.setText("Cerrar");
        cerrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPedidoActionPerformed(evt);
            }
        });

        repartoDomic.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        repartoDomic.setForeground(new java.awt.Color(255, 255, 255));
        repartoDomic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        repartoDomic.setText("Reparto/Domic.(+1€)");

        butonReparto.add(butonSiReparto);
        butonSiReparto.setForeground(new java.awt.Color(255, 255, 255));
        butonSiReparto.setText("Si");
        butonSiReparto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonSiRepartoActionPerformed(evt);
            }
        });

        butonReparto.add(butonNoReparto);
        butonNoReparto.setForeground(new java.awt.Color(255, 255, 255));
        butonNoReparto.setText("No");
        butonNoReparto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonNoRepartoActionPerformed(evt);
            }
        });

        tituloMostrarResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloMostrarResultado.setForeground(new java.awt.Color(255, 255, 255));
        tituloMostrarResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMostrarResultado.setText("Total €:");

        butonTipoHamburguesa.add(hamburguesaPollo);
        hamburguesaPollo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hamburguesaPollo.setForeground(new java.awt.Color(255, 255, 255));
        hamburguesaPollo.setText("Pollo");
        hamburguesaPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburguesaPolloActionPerformed(evt);
            }
        });

        butonTipoHamburguesa.add(hamburguesaCerdo);
        hamburguesaCerdo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hamburguesaCerdo.setForeground(new java.awt.Color(255, 255, 255));
        hamburguesaCerdo.setText("Cerdo");

        butonTipoHamburguesa.add(hamburguesaTernera);
        hamburguesaTernera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hamburguesaTernera.setForeground(new java.awt.Color(255, 255, 255));
        hamburguesaTernera.setText("Ternera(+1€)");

        butonTipoHamburguesa.add(hamburguesaVegana);
        hamburguesaVegana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hamburguesaVegana.setForeground(new java.awt.Color(255, 255, 255));
        hamburguesaVegana.setText("Vegana(+1€)");

        butonTipoPan.add(panNormal);
        panNormal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panNormal.setForeground(new java.awt.Color(255, 255, 255));
        panNormal.setText("Normal");

        butonTipoPan.add(panIntegral);
        panIntegral.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panIntegral.setForeground(new java.awt.Color(255, 255, 255));
        panIntegral.setText("integral");
        panIntegral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        butonTipoPan.add(panCentano);
        panCentano.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panCentano.setForeground(new java.awt.Color(255, 255, 255));
        panCentano.setText("Centano");
        panCentano.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        butonTipoBebida.add(bebidaCocaCola);
        bebidaCocaCola.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bebidaCocaCola.setForeground(new java.awt.Color(255, 255, 255));
        bebidaCocaCola.setText("Coca-Cola");

        butonTipoBebida.add(bebidaLimon);
        bebidaLimon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bebidaLimon.setForeground(new java.awt.Color(255, 255, 255));
        bebidaLimon.setText("Limón");
        bebidaLimon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bebidaLimon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        butonTipoBebida.add(bebidaNaranja);
        bebidaNaranja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bebidaNaranja.setForeground(new java.awt.Color(255, 255, 255));
        bebidaNaranja.setText("Naranja");

        butonTipoBebida.add(bebidaAgua);
        bebidaAgua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bebidaAgua.setForeground(new java.awt.Color(255, 255, 255));
        bebidaAgua.setText("Agua");

        butonTipoBebida.add(bebidaCerveza);
        bebidaCerveza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bebidaCerveza.setForeground(new java.awt.Color(255, 255, 255));
        bebidaCerveza.setText("Cerveza");

        butonTipoBebida.add(bebidaVino);
        bebidaVino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bebidaVino.setForeground(new java.awt.Color(255, 255, 255));
        bebidaVino.setText("Vino");
        bebidaVino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        butonTipoPatatas.add(patatasFritas);
        patatasFritas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        patatasFritas.setForeground(new java.awt.Color(255, 255, 255));
        patatasFritas.setText("Fritas");

        butonTipoPatatas.add(patatasGajo);
        patatasGajo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        patatasGajo.setForeground(new java.awt.Color(255, 255, 255));
        patatasGajo.setText("Gajo(0,50€)");

        calcularPedido.setBackground(new java.awt.Color(0, 255, 51));
        calcularPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        calcularPedido.setText("Calcular Pedido:");
        calcularPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularPedidoActionPerformed(evt);
            }
        });

        novoPedido.setBackground(new java.awt.Color(255, 255, 255));
        novoPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        novoPedido.setText("Novo Pedido:");
        novoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoPedidoActionPerformed(evt);
            }
        });

        panelElegirHamburguesa.setBackground(new java.awt.Color(204, 255, 204));

        tituloHamburgueseria1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        tituloHamburgueseria1.setForeground(new java.awt.Color(0, 51, 0));
        tituloHamburgueseria1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloHamburgueseria1.setText("Elegir Hamburguesa:");

        javax.swing.GroupLayout panelElegirHamburguesaLayout = new javax.swing.GroupLayout(panelElegirHamburguesa);
        panelElegirHamburguesa.setLayout(panelElegirHamburguesaLayout);
        panelElegirHamburguesaLayout.setHorizontalGroup(
            panelElegirHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamburgueseria1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelElegirHamburguesaLayout.setVerticalGroup(
            panelElegirHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamburgueseria1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        panelElegirPan.setBackground(new java.awt.Color(204, 255, 204));

        tituloHamburgueseria2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        tituloHamburgueseria2.setForeground(new java.awt.Color(0, 51, 0));
        tituloHamburgueseria2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloHamburgueseria2.setText("Elegir Pan:");

        javax.swing.GroupLayout panelElegirPanLayout = new javax.swing.GroupLayout(panelElegirPan);
        panelElegirPan.setLayout(panelElegirPanLayout);
        panelElegirPanLayout.setHorizontalGroup(
            panelElegirPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamburgueseria2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelElegirPanLayout.setVerticalGroup(
            panelElegirPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamburgueseria2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        panelElegirBebida.setBackground(new java.awt.Color(204, 255, 204));

        tituloHamburgueseria3.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        tituloHamburgueseria3.setForeground(new java.awt.Color(0, 51, 0));
        tituloHamburgueseria3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloHamburgueseria3.setText("Elegir Bebida:");

        javax.swing.GroupLayout panelElegirBebidaLayout = new javax.swing.GroupLayout(panelElegirBebida);
        panelElegirBebida.setLayout(panelElegirBebidaLayout);
        panelElegirBebidaLayout.setHorizontalGroup(
            panelElegirBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamburgueseria3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelElegirBebidaLayout.setVerticalGroup(
            panelElegirBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamburgueseria3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        panelElegirPatatas.setBackground(new java.awt.Color(204, 255, 204));

        tituloHamburgueseria4.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        tituloHamburgueseria4.setForeground(new java.awt.Color(0, 51, 0));
        tituloHamburgueseria4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloHamburgueseria4.setText("Elegir Patatas:");

        javax.swing.GroupLayout panelElegirPatatasLayout = new javax.swing.GroupLayout(panelElegirPatatas);
        panelElegirPatatas.setLayout(panelElegirPatatasLayout);
        panelElegirPatatasLayout.setHorizontalGroup(
            panelElegirPatatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamburgueseria4, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        panelElegirPatatasLayout.setVerticalGroup(
            panelElegirPatatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamburgueseria4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        panelExtrasAdicionales.setBackground(new java.awt.Color(204, 255, 204));

        tituloHamburgueseria5.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        tituloHamburgueseria5.setForeground(new java.awt.Color(0, 51, 0));
        tituloHamburgueseria5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloHamburgueseria5.setText("Extras/Adicionales");

        javax.swing.GroupLayout panelExtrasAdicionalesLayout = new javax.swing.GroupLayout(panelExtrasAdicionales);
        panelExtrasAdicionales.setLayout(panelExtrasAdicionalesLayout);
        panelExtrasAdicionalesLayout.setHorizontalGroup(
            panelExtrasAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamburgueseria5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelExtrasAdicionalesLayout.setVerticalGroup(
            panelExtrasAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloHamburgueseria5, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        mostrarTotal.setColumns(20);
        mostrarTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mostrarTotal.setRows(5);
        jScrollPane1.setViewportView(mostrarTotal);

        panelElegirSalsas.setBackground(new java.awt.Color(204, 255, 204));

        tituloSalsas.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        tituloSalsas.setForeground(new java.awt.Color(0, 51, 0));
        tituloSalsas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloSalsas.setText("Elegir Salsas:");

        javax.swing.GroupLayout panelElegirSalsasLayout = new javax.swing.GroupLayout(panelElegirSalsas);
        panelElegirSalsas.setLayout(panelElegirSalsasLayout);
        panelElegirSalsasLayout.setHorizontalGroup(
            panelElegirSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloSalsas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelElegirSalsasLayout.setVerticalGroup(
            panelElegirSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloSalsas, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        butonTipoSalsa.add(elegirSalsaKetchup);
        elegirSalsaKetchup.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        elegirSalsaKetchup.setForeground(new java.awt.Color(255, 255, 255));
        elegirSalsaKetchup.setText("Ketchup(+0,25€)");
        elegirSalsaKetchup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirSalsaKetchupActionPerformed(evt);
            }
        });

        butonTipoSalsa.add(elegirSalsaBarbacoa);
        elegirSalsaBarbacoa.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        elegirSalsaBarbacoa.setForeground(new java.awt.Color(255, 255, 255));
        elegirSalsaBarbacoa.setText("Barbacoa(+0,25€)");
        elegirSalsaBarbacoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirSalsaBarbacoaActionPerformed(evt);
            }
        });

        butonTipoSalsa.add(elegirSalsaMostaza);
        elegirSalsaMostaza.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        elegirSalsaMostaza.setForeground(new java.awt.Color(255, 255, 255));
        elegirSalsaMostaza.setText("Mostaza(+0,25€)");
        elegirSalsaMostaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirSalsaMostazaActionPerformed(evt);
            }
        });

        butonTipoSalsa.add(elegirSalsaNo);
        elegirSalsaNo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        elegirSalsaNo.setForeground(new java.awt.Color(255, 255, 255));
        elegirSalsaNo.setText("No");
        elegirSalsaNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirSalsaNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addComponent(descuentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butonIVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(tituloMostrarResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pantallaMostrarArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelGeneralLayout.createSequentialGroup()
                                .addComponent(hamburguesaPollo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hamburguesaCerdo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hamburguesaVegana)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hamburguesaTernera))
                            .addComponent(panelElegirHamburguesa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelGeneralLayout.createSequentialGroup()
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelGeneralLayout.createSequentialGroup()
                                        .addComponent(butonSiHambur)
                                        .addGap(18, 18, 18)
                                        .addComponent(butonNoHambur))
                                    .addComponent(doubleHambur))
                                .addGap(18, 18, 18)
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(extraQueso)
                                    .addGroup(panelGeneralLayout.createSequentialGroup()
                                        .addComponent(butonSiQueso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(butonNoQueso)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(extraPatatas)
                                    .addGroup(panelGeneralLayout.createSequentialGroup()
                                        .addComponent(butonSiPatatas)
                                        .addGap(24, 24, 24)
                                        .addComponent(butonNoPatatas)))
                                .addGap(18, 18, 18)
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(repartoDomic, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                                        .addComponent(butonSiReparto)
                                        .addGap(18, 18, 18)
                                        .addComponent(butonNoReparto))))
                            .addComponent(panelExtrasAdicionales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGeneralLayout.createSequentialGroup()
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(panelElegirPatatas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGeneralLayout.createSequentialGroup()
                                        .addComponent(patatasFritas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(patatasGajo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelGeneralLayout.createSequentialGroup()
                                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(elegirSalsaKetchup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(elegirSalsaBarbacoa, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(elegirSalsaMostaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(elegirSalsaNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(panelElegirSalsas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(panelGeneralLayout.createSequentialGroup()
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bebidaCocaCola, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bebidaAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bebidaNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bebidaCerveza, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bebidaVino, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bebidaLimon, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(panelElegirBebida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelElegirPan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGeneralLayout.createSequentialGroup()
                                .addComponent(panNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(panIntegral, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panCentano)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addComponent(calcularPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(novoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cerrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addComponent(panelElegirHamburguesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hamburguesaPollo)
                            .addComponent(hamburguesaCerdo)
                            .addComponent(hamburguesaVegana)
                            .addComponent(hamburguesaTernera))
                        .addGap(18, 18, 18)
                        .addComponent(panelElegirPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(panNormal)
                            .addComponent(panIntegral)
                            .addComponent(panCentano))
                        .addGap(18, 18, 18)
                        .addComponent(panelElegirBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bebidaCocaCola)
                            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bebidaNaranja)
                                .addComponent(bebidaLimon)))
                        .addGap(18, 18, 18)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bebidaVino)
                                .addComponent(bebidaAgua))
                            .addComponent(bebidaCerveza))
                        .addGap(18, 18, 18)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelElegirPatatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelElegirSalsas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGeneralLayout.createSequentialGroup()
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(elegirSalsaKetchup)
                                    .addComponent(elegirSalsaMostaza))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(elegirSalsaBarbacoa)
                                    .addComponent(elegirSalsaNo)))
                            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(patatasFritas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(patatasGajo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelExtrasAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pantallaMostrarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doubleHambur)
                            .addComponent(extraQueso)
                            .addComponent(repartoDomic)
                            .addComponent(extraPatatas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butonSiHambur, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonNoHambur, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonNoQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonSiQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonSiPatatas, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonNoPatatas, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonSiReparto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonNoReparto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calcularPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(novoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cerrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addComponent(tituloMostrarResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descuentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butonIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hamburguesaPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburguesaPolloActionPerformed
      
    }//GEN-LAST:event_hamburguesaPolloActionPerformed

    private void butonNoRepartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonNoRepartoActionPerformed
        
    }//GEN-LAST:event_butonNoRepartoActionPerformed

    private void butonSiRepartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonSiRepartoActionPerformed
        
    }//GEN-LAST:event_butonSiRepartoActionPerformed

    private void cerrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPedidoActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarPedidoActionPerformed

    private void butonIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonIVAActionPerformed
        //OPERACIONES PARA RECOGER LOS ARRAYLIST Y HACER LAS CAPTURA DE PANTALLA
        //CON LOS TEXTOS Y PRECIOS DE CADA PRODUCTO CON IVA
        
        valores.clear();
        mostrarTotal.setText("===TOTAL CON IVA===\n");
        valores.add(8.00);
        
        DecimalFormat decimales = new DecimalFormat("0.##");
        decimales.setRoundingMode(RoundingMode.DOWN);
        
        //VARIAVEL PARA EL CALCULO DEL IVA DE 21%
        double conta = 0;
        double iva = 21;
        double operac;
        double total;
        
        //BUCLE PARA RECOGER LOS VALORES DE LAS HAMBURGUESAS
        if (elegirHamburguesa()){
            for(int i = 0; i < this.valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER LOS VALORES DEL TIPO DE PATATAS
        if(elegirPatatas()){
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER LOS VALORES DE HAMBURGUESAS DOBLE
        if(dobleHamburguesa()){
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER LOS VALORES DE EXTRA DE QUESO
        if(extraQueso()){
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER LOS VALORES DE EXTRA DE PATATAS
        if(extraPatatas()){
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER LOS VALORES DE REPARTO A DOMICILIO
        if(repartoDomicilio()){
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER LOS VALORES DE LAS SALSAS
        if(elegirSalsas()){
            for(int i = 0; i < valores.size(); i++){
                conta = conta + valores.get(i);
                
                operac = ((iva * conta) / 100);
                total = conta + operac;

                mostrarTotal.append(String.valueOf(decimales.format(total)) + "€");
                mostrarTotal.append("\n");

            }
        }
    }//GEN-LAST:event_butonIVAActionPerformed

    private void butonNoPatatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonNoPatatasActionPerformed
        
    }//GEN-LAST:event_butonNoPatatasActionPerformed

    private void butonSiPatatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonSiPatatasActionPerformed
       
    }//GEN-LAST:event_butonSiPatatasActionPerformed

    private void butonNoQuesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonNoQuesoActionPerformed
        
    }//GEN-LAST:event_butonNoQuesoActionPerformed

    private void butonSiQuesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonSiQuesoActionPerformed
        
    }//GEN-LAST:event_butonSiQuesoActionPerformed

    private void butonNoHamburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonNoHamburActionPerformed
        
    }//GEN-LAST:event_butonNoHamburActionPerformed

    private void butonSiHamburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonSiHamburActionPerformed
        
    }//GEN-LAST:event_butonSiHamburActionPerformed

    private void novoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoPedidoActionPerformed
        this.nuevoPedido();
    }//GEN-LAST:event_novoPedidoActionPerformed

    private void calcularPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularPedidoActionPerformed
        //OPERACIONES PARA RECOGER LOS ARRAYLIST Y HACER LAS CAPTURA DE PANTALLA
        //CON LOS TEXTOS Y PRECIOS DE CADA PRODUCTO
        
        valores.clear();
        pedido.clear();
        pantallaMostrar.setText("");
        mostrarTotal.setText("===TOTAL PRECIO DE VENTA===\n");
        
        DecimalFormat decimales = new DecimalFormat("0.##");
        decimales.setRoundingMode(RoundingMode.DOWN);
        
        //TITULO DE LA PANTALLA Y VALOR FIJO DEL MENÚ(8,00€)
        pedido.add("===MENÚ PEDIDO===");
        valores.add(8.00);
        
        //BUCLE PARA RECOGER LOS TIPOS DE CARNE DE LAS HAMBURGUESAS Y
        //LOS VALORES
        if (elegirHamburguesa()){
            for(int i = 0; i < pedido.size(); i++){
            }
            for(int i = 0; i < valores.size(); i++){
            }
        } 
        
        //BUCLE PARA RECOGER LOS TIPOS DE PAN
        if(elegirPan()){
            for(int i = 0; i < pedido.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER LOS TIPOS DE BEBIDA
        if(elegirBebida()){
            for(int i = 0; i < pedido.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER EL TIPO DE PATATAS Y LOS VALORES 
        if(elegirPatatas()){
            for(int i = 0; i < pedido.size(); i++){
            }
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER HAMBURGUESA DOBLE Y EL VALOR
        if(dobleHamburguesa()){
            for(int i = 0; i < pedido.size(); i++){
            }
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER EXTRA DE QUESO Y EL VALOR 
        if(extraQueso()){
            for(int i = 0; i < pedido.size(); i++){
            }
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER EXTRA DE PATATAS Y EL VALOR 
        if(extraPatatas()){
            for(int i = 0; i < pedido.size(); i++){
            }
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER REPARTO A DOMICILIO Y EL VALOR 
        if(repartoDomicilio()){
            for(int i = 0; i < pedido.size(); i++){
            }
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER TIPOS DE SALSAS Y EL VALORES 
        if(elegirSalsas()){
            double conta = 0;
            for(int i = 0; i < pedido.size(); i++){
                pantallaMostrar.append(pedido.get(i));
                pantallaMostrar.append("\n");
            } 
            for(int i = 0; i < valores.size(); i++){
                conta = conta + valores.get(i);
                mostrarTotal.append(String.valueOf(decimales.format(conta))+"€");
                mostrarTotal.append("\n");
            }
        } 
    }//GEN-LAST:event_calcularPedidoActionPerformed

    private void descuentoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descuentoClienteActionPerformed
        //OPERACIONES PARA CREAR EL DESCUENTO DE 20%
        
        valores.clear();
        mostrarTotal.setText("===TOTAL CLIENTE VIP===\n");
        valores.add(8.00);
        
        DecimalFormat decimales = new DecimalFormat("0.##");
        decimales.setRoundingMode(RoundingMode.DOWN);
        
        //VARIAVEL PARA EL CALCULO DE LA PORCENTAJE
        double conta = 0;
        double descue = 20;
        double operac;
        double total;
        
        //BUCLE PARA RECOGER LOS VALORES DE CARNE DE LAS HAMBURGUESAS
        if (elegirHamburguesa()){
            for(int i = 0; i < valores.size(); i++){
                //conta = conta + cuenta.get(i);
                //pantallaMostrar.append("\n");
            }
        }
        
        //BUCLE PARA RECOGER EL VALOR DE LOS TIPO DE PATATAS
        if(elegirPatatas()){
            for(int i = 0; i < valores.size(); i++){
                //conta = conta + cuenta.get(i);
                //pantallaMostrar.append("\n");
            }
        }
        
        //BUCLE PARA RECOGER EL VALOR DE LA HAMBURGUESA DOBLE 
        if(dobleHamburguesa()){
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER EL VALOR DE EXTRA DE QUESO
        if(extraQueso()){
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER EL VALOR DE EXTRA DE PATATAS
        if(extraPatatas()){
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER EL VALOR DE REPARTO A DOMICILIO
        if(repartoDomicilio()){
            for(int i = 0; i < valores.size(); i++){
            }
        }
        
        //BUCLE PARA RECOGER EL VALOR DE LAS SALSAS
        if(elegirSalsas()){
            for(int i = 0; i < valores.size(); i++){
                conta = conta + valores.get(i);
                
                //CALCULO PARA HACER EL DESCUENTO DE 20%
                operac = ((descue * conta) / 100);
                total = conta - operac;
                
                //MOSTRAR EN PANTALLA LOS VALORES
                mostrarTotal.append(String.valueOf(decimales.format(total)) + "€");
                mostrarTotal.append("\n");
            }
        }
    }//GEN-LAST:event_descuentoClienteActionPerformed

    private void elegirSalsaKetchupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirSalsaKetchupActionPerformed
        
    }//GEN-LAST:event_elegirSalsaKetchupActionPerformed

    private void elegirSalsaBarbacoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirSalsaBarbacoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elegirSalsaBarbacoaActionPerformed

    private void elegirSalsaMostazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirSalsaMostazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elegirSalsaMostazaActionPerformed

    private void elegirSalsaNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirSalsaNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elegirSalsaNoActionPerformed
    
    //CERRAR SECCIÓN Y INICIAR EL PROGRAMA DESDE EL PRINCIPIO
    private void nuevoPedido(){
        pantallaMostrar.setText(" ");
        butonTipoHamburguesa.clearSelection();
        butonTipoPan.clearSelection();
        butonTipoBebida.clearSelection();
        butonTipoPatatas.clearSelection();
        butonDobleHamb.clearSelection();
        butonExtraQueso.clearSelection();
        butonExtraPatatas.clearSelection();
        butonReparto.clearSelection();
        mostrarTotal.setText(" ");
        butonTipoSalsa.clearSelection();
    }
    
    //CREANDO OPICIONALES DE LOS TIPOS DE CARNES DE LAS HAMBURGUESAS
    private boolean elegirHamburguesa(){
        boolean hamburguesa = true;
        
        try {
            if(hamburguesaPollo.isSelected()){
                pedido.add("Hamburguesa de Pollo");
                } else if(hamburguesaCerdo.isSelected()) {
                    pedido.add("Hamburguesa de Cerdo"); 
                    } else if(hamburguesaVegana.isSelected()) {
                        pedido.add("Hamburguesa de Vegana");
                        valores.add(1.0);
                        } else if(hamburguesaTernera.isSelected()) {
                            pedido.add("Hamburguesa de Ternera");
                            valores.add(1.0);
                        } 
                        else {
                            JOptionPane.showMessageDialog(this, "¡Seleccione todas las opiciones del Menú!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                            hamburguesa = false;    
                        }
            //INSERI EL CONTROL DE EXCEPCIONES, PERO HICE ALGUNA COSA MALA QUE NO VA...
            } catch (Exception carne){
                JOptionPane.showMessageDialog(null, "Seleccione los opicionales del Menú", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        return hamburguesa;
    }
    
    //CREANDO OPICIONALES DE LOS TIPOS DE PAN
    private boolean elegirPan() {
        boolean pan = true;
        
        if(panNormal.isSelected()){
            pedido.add("Pan Normal");
            } else if(panIntegral.isSelected()) {
                    pedido.add("Pan Integral"); 
                    } else if(panCentano.isSelected()) {
                        pedido.add("Pan Centano");
                    } else {
                        pan = false;    
                    }
        return pan;
    }
    
    //CREANDO OPICIONALES DE LOS TIPOS DE BEBIDAS
    private boolean elegirBebida(){
        boolean bebidas = true;
        
        if(bebidaCocaCola.isSelected()){
            pedido.add("Refresco Coca-Cola");
            } else if(bebidaNaranja.isSelected()) {
                    pedido.add("Refresco de Naranja"); 
                    } else if(bebidaLimon.isSelected()) {
                        pedido.add("Refresco de Limón");
                        } else if(bebidaAgua.isSelected()) {
                            pedido.add("Agua");
                            } else if(bebidaCerveza.isSelected()) {
                                pedido.add("Cerveza");
                                } else if(bebidaVino.isSelected()){
                                    pedido.add("Vino");
                    } else {
                        bebidas = false;    
                    }
        return bebidas;
    }
    
    //CREANDO OPICIÓN DE PATATAS FRITAS O GAJO
    private boolean elegirPatatas() {
        boolean patatas = true;
        
        if(patatasFritas.isSelected()){
            pedido.add("Patatas Fritas");
            } else if(patatasGajo.isSelected()) {
                    pedido.add("Patatas Gajo");
                    valores.add(0.50);
                    } else {
                        patatas = false;    
                    }
        return patatas;
    }
    
    //CREANDO OPICIÓN DE DOBLE HAMBURGUESA
    private boolean dobleHamburguesa() {
        boolean dobleHamb = true;
        
        if(butonSiHambur.isSelected()){
            pedido.add("Hamburguesa Doble");
            valores.add(2.00);
            } else if(butonNoHambur.isSelected()) {
                    pedido.add("");
                    } else {
                        dobleHamb = false; 
            }
        return dobleHamb;
    }
    
    //CREANDO OPICIÓN DE EXTRA DE QUESO
    private boolean extraQueso() {
        boolean extQueso = true;
        
        if(butonSiQueso.isSelected()){
            pedido.add("Extra de Queso");
            valores.add(0.50);
            } else if(butonNoQueso.isSelected()) {
                    pedido.add("");
                    } else {
                        extQueso = false;
            }
        return extQueso;
    }
    
    //CREANDO OPICIÓN DE EXTRA DE PATATAS
    private boolean extraPatatas() {
        boolean extPatatas = true;
        
        if(butonSiPatatas.isSelected()){
            pedido.add("Extra de Patatas");
            valores.add(1.00);
            } else if(butonNoPatatas.isSelected()) {
                    pedido.add("");
                    } else {
                        extPatatas = false;
            }
        return extPatatas;
    }
    
    //CREANDO OPICIÓN DE REPARTO A DOMICILIO
    private boolean repartoDomicilio() {
        boolean reparto = true;
        
        if(butonSiReparto.isSelected()){
            pedido.add("Reparto a Domicilio: Si");
            valores.add(1.00);
            } else if(butonNoPatatas.isSelected()) {
                    pedido.add("");
                    } else {
                        reparto = false;
            }
        return reparto;
    }
    
    //CREANDO OPICIÓN PARA ELEGIR SALSA
    private boolean elegirSalsas(){
        
        boolean salsas = true;
         
        if(elegirSalsaKetchup.isSelected()){
            pedido.add("Salsa Ketchup");
            valores.add(0.25);
            } else if(elegirSalsaBarbacoa.isSelected()){
                pedido.add("Salsa Barbacoa");
                valores.add(0.25); 
                } else if (elegirSalsaMostaza.isSelected()){
                    pedido.add("Salsa Mostaza");
                    valores.add(0.25);
                    } else if (elegirSalsaNo.isSelected()){
                        pedido.add(" ");
                        } else {
                            salsas = false;
                        }
        return salsas;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try{
            App_Hamburgueseria.setDefaultLookAndFeelDecorated(true);
            //javax.swing.UIManager.setLookAndFeel('com.sun.java.swing.plaf.windows.WindowsLookAndFeel');        
            }catch (Exception e){
                e.printStackTrace();
            }
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App_Hamburgueseria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App_Hamburgueseria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App_Hamburgueseria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App_Hamburgueseria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App_Hamburgueseria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bebidaAgua;
    private javax.swing.JRadioButton bebidaCerveza;
    private javax.swing.JRadioButton bebidaCocaCola;
    private javax.swing.JRadioButton bebidaLimon;
    private javax.swing.JRadioButton bebidaNaranja;
    private javax.swing.JRadioButton bebidaVino;
    private javax.swing.ButtonGroup butonDobleHamb;
    private javax.swing.ButtonGroup butonExtraPatatas;
    private javax.swing.ButtonGroup butonExtraQueso;
    private javax.swing.JButton butonIVA;
    private javax.swing.JRadioButton butonNoHambur;
    private javax.swing.JRadioButton butonNoPatatas;
    private javax.swing.JRadioButton butonNoQueso;
    private javax.swing.JRadioButton butonNoReparto;
    private javax.swing.ButtonGroup butonReparto;
    private javax.swing.JRadioButton butonSiHambur;
    private javax.swing.JRadioButton butonSiPatatas;
    private javax.swing.JRadioButton butonSiQueso;
    private javax.swing.JRadioButton butonSiReparto;
    private javax.swing.ButtonGroup butonTipoBebida;
    private javax.swing.ButtonGroup butonTipoHamburguesa;
    private javax.swing.ButtonGroup butonTipoPan;
    private javax.swing.ButtonGroup butonTipoPatatas;
    private javax.swing.ButtonGroup butonTipoSalsa;
    private javax.swing.JButton calcularPedido;
    private javax.swing.JButton cerrarPedido;
    private javax.swing.JButton descuentoCliente;
    private javax.swing.JLabel doubleHambur;
    private javax.swing.JCheckBox elegirSalsaBarbacoa;
    private javax.swing.JCheckBox elegirSalsaKetchup;
    private javax.swing.JCheckBox elegirSalsaMostaza;
    private javax.swing.JCheckBox elegirSalsaNo;
    private javax.swing.JLabel extraPatatas;
    private javax.swing.JLabel extraQueso;
    private javax.swing.JRadioButton hamburguesaCerdo;
    private javax.swing.JRadioButton hamburguesaPollo;
    private javax.swing.JRadioButton hamburguesaTernera;
    private javax.swing.JRadioButton hamburguesaVegana;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mostrarTotal;
    private javax.swing.JButton novoPedido;
    private javax.swing.JRadioButton panCentano;
    private javax.swing.JRadioButton panIntegral;
    private javax.swing.JRadioButton panNormal;
    private javax.swing.JPanel panelElegirBebida;
    private javax.swing.JPanel panelElegirHamburguesa;
    private javax.swing.JPanel panelElegirPan;
    private javax.swing.JPanel panelElegirPatatas;
    private javax.swing.JPanel panelElegirSalsas;
    private javax.swing.JPanel panelExtrasAdicionales;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextArea pantallaMostrar;
    private javax.swing.JScrollPane pantallaMostrarArea;
    private javax.swing.JRadioButton patatasFritas;
    private javax.swing.JRadioButton patatasGajo;
    private javax.swing.JLabel repartoDomic;
    private javax.swing.JLabel tituloHamburgueseria;
    private javax.swing.JLabel tituloHamburgueseria1;
    private javax.swing.JLabel tituloHamburgueseria2;
    private javax.swing.JLabel tituloHamburgueseria3;
    private javax.swing.JLabel tituloHamburgueseria4;
    private javax.swing.JLabel tituloHamburgueseria5;
    private javax.swing.JLabel tituloMostrarResultado;
    private javax.swing.JLabel tituloSalsas;
    // End of variables declaration//GEN-END:variables
}
